### ISSUE TITLE
keywords2pickle not found 

### ISSUE THREAD

**Issue by yogesh-0586** [debjyoti385/QuestionAnswerNLP#1]
As per prepare.sh added hard coded path like this 
cp -r /home/debjyotp/important/qcdata .
echo "## FETCH COMPLETE ##"
echo "## FETCH developset DATA ##"
cp -r /home/debjyotp/important/developset .
echo "## PREPARING input.txt  ##"
cd developset

can you add this in project because of this it show following error :
Traceback (most recent call last):
  File "qa.py", line 112, in <module>
    q_classifier = QuestionClassifier.get_classifier()
  File "modules/QuestionClassifier.py", line 217, in get_classifier
    classifier = QuestionClassifier(fine_grain)
  File "modules/QuestionClassifier.py", line 178, in __init__
    self.keywordlist2 = load_keywords()
  File "modules/keywords_pickle_builder.py", line 26, in load_keywords
    save_keywords(keywords=keywords)
  File "modules/keywords_pickle_builder.py", line 31, in save_keywords
    with open('qcdata/keywords2pickle', 'wb') as fout:
IOError: [Errno 2] No such file or directory: 'qcdata/keywords2pickle'

**Comment by bachhi** [comment]
Please upload the data files

**Comment by amandalmia14** [comment]
@debjyoti385 please update the data files. 
Thanks.

**Comment by amandalmia** [comment]
@debjyoti385 Have you uploaded the data files?
As I am not able to find the files in your repo !!

**Comment by amandalmia14** [comment]
@debjyoti385 have you added the files? As I am not able to see in your repo?
Thanks.

**Comment by suvarawg10** [comment]
please update the data files.
Thanks.

**Comment by suvarawg10** [comment]
I had the same problem I solved it by following steps

http://cogcomp.cs.illinois.edu/Data/QA/QC/QC.tar

download it from this link

and extract into qcdata/publish/lists

also download stopwords and punkt using cmd 

 python -m nltk.downloader stopwords

 python -m nltk.downloader punkt


Also Download training dataset  and question set and put them into qcdata/

https://cogcomp.seas.upenn.edu/Data/QA/QC/train_5500.label
https://cogcomp.seas.upenn.edu/Data/QA/QC/TREC_10.label 
 
Thanks
